name: Typos Check
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*'

jobs:
  run:
    name: Spell Check with Typos on Changed Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: '**/database/**'

      - name: Check spelling of changed files (excluding /database/)
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: crate-ci/typos@master
        with:
          files: |
            ${{ steps.changed-files.outputs.all_changed_files }}