name: Playwright Tests
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  test:
    if: github.repository == 'activepieces/activepieces'
    timeout-minutes: 10
    runs-on: ubuntu-latest
    env:
      AP_TEST_EMAIL: ${{ secrets.AP_TEST_EMAIL }}
      AP_TEST_PASSWORD: ${{ secrets.AP_TEST_PASSWORD }}
      AP_TEST_CHANNEL: ${{ secrets.AP_TEST_CHANNEL }}
      AP_TEST_URL: ${{ secrets.AP_TEST_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
        working-directory: packages/tests-e2e
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: packages/tests-e2e
      - name: Run Playwright tests
        run: npx playwright test
        working-directory: packages/tests-e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
          working-directory: packages/tests-e2e
      - name: Notify webhook on failure
        if: failure()
        run: |
          curl -X POST 'https://api.instatus.com/v3/integrations/webhook/clh20dtiy132156wsnc3oshf7tp' \
          -H 'Content-Type: application/json' \
          -d '{"trigger": "down"}'
