name: Staging Automate Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'release/**'

jobs:
  Release:
    runs-on: depot-ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set RELEASE env var from package.json
        run: echo RELEASE=$(node --print "require('./package.json').version") >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Depot CLI
        uses: depot/setup-action@v1

      - name: Build and push
        uses: depot/build-push-action@v1
        with:
          project: du7O4b0e8P
          token: ${{ secrets.DEPOT_PROJECT_TOKEN }}
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            ghcr.io/activepieces/activepieces-cloud:${{ env.RELEASE }}.${{ github.sha }}.beta

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ops.key
          chmod 600 ~/.ssh/ops.key
          cat >>~/.ssh/config <<END
          Host ops
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/ops.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.DEV_OPS_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.DEV_OPS_HOST }}

      - name: Deploy
        run: |
          ssh ops -t -t 'bash -ic "cd mrsk/stg && kamal setup --version ${{ env.RELEASE }}.${{ github.sha }}.beta --skip-push; exit"'
