name: Unified Automate Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [merged]
    branches:
      - main
    merged: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/preview-server.key
          chmod 600 ~/.ssh/preview-server.key
          cat >>~/.ssh/config <<END
          Host preview-server
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/preview-server.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.PRE_PROD_USERNAME }}
          SSH_KEY: ${{ secrets.PREVIEW_SSH_KEY }}
          SSH_HOST: ${{ secrets.PREVIEW_HOST }}

      - name: Run Pre-Prod Setup
        run: |
          ssh preview-server -t -t 'bash -ic "node dist/index.js setup main preprod env.preprod; exit"'

      - name: Run Community Setup
        run: |
          ssh preview-server -t -t 'bash -ic "node dist/index.js setup main ce env.ce; exit"'

      - name: Run Enterprise Setup
        run: |
          ssh preview-server -t -t 'bash -ic "node dist/index.js setup main ee env.ee; exit"'